---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.158
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80