---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pv-claim
  namespace: pihole
  labels:
    app: iphole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi